import NavbarComponent from "@/components/NavbarComponent";
import "../globals.css";
import SidebarComponent from "@/components/SidebarComponent";
import MonthlyStatisticsComponent from "@/components/MonthlyStatisticsComponent";
import ListBoardComponentHeader from "@/components/ListBoardComponentHeader";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-SFProDisplay">
        <div className="flex">
          <div className="w-[20vw]">
            <SidebarComponent />
          </div>
          <div className="w-[100vw]">
            <div>
              <NavbarComponent />
            </div>
            <div className="flex m-5">
              <div className="w-[70%] mr-5">
              <ListBoardComponentHeader/>
                {children}
              </div>
              <div className="w-[30%]">
                <MonthlyStatisticsComponent/>
              </div>
            </div>
          </div>
        </div>

      </body>
    </html>
  );
}